# Generated by Django 6.0.7 on 2026-07-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
